#!/usr/bin/env python3.9

import sys

file_path = sys.argv[1]
file_name = file_path.split("/")[-1]

class_name = ''.join(word.title() for word in file_name.split('_'))

script = f"""
from app.utils import spec, RequestHandler

class {class_name}(RequestHandler):
    pass

def setup(app):
    return [(f"/api/v{{app.version}}/{file_name}", {class_name}, app.args)]

"""

with open(f"./app/extensions/{file_path}.py", "w") as f:
    f.write(script)

print(f"Created cog at ./app/extensions/{file_path}.py")
