on: push
name: pyright
jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v2
      - uses: jakebailey/pyright-action@v1
        with:
          lib: true
          python-version: 3.9.5
