on: push
name: pyright
jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - uses: jakebailey/pyright-action@v1
        with:
          lib: true
          python-version: 3.9.5
